# Generated by Django 6.0.3 on 2026-03-04 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
            },
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_url', models.URLField(default='https://www.tiktok.com/@khamish92/live')),
                ('num_viewers', models.IntegerField(default=3)),
                ('headless', models.BooleanField(default=True)),
                ('page_load_timeout', models.IntegerField(default=60000)),
                ('element_wait_timeout', models.IntegerField(default=10000)),
                ('session_max_duration', models.IntegerField(default=1800)),
                ('keepalive_min_interval', models.IntegerField(default=30)),
                ('keepalive_max_interval', models.IntegerField(default=60)),
                ('max_retry_attempts', models.IntegerField(default=3)),
                ('base_retry_delay', models.FloatField(default=2.0)),
                ('window_width', models.IntegerField(default=1366)),
                ('window_height', models.IntegerField(default=768)),
                ('debug_screenshots', models.BooleanField(default=True)),
                ('screenshot_dir', models.CharField(default='screenshots', max_length=255)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Configuration',
                'verbose_name_plural': 'Bot Configurations',
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='started', max_length=20)),
                ('viewers_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_management.botconfiguration')),
            ],
            options={
                'verbose_name': 'Bot Session',
                'verbose_name_plural': 'Bot Sessions',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.IntegerField()),
                ('status', models.CharField(default='starting', max_length=20)),
                ('comments_sent', models.IntegerField(default=0)),
                ('reactions_made', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('proxy_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_management.proxy')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='bot_management.botsession')),
            ],
            options={
                'verbose_name': 'Viewer',
                'verbose_name_plural': 'Viewers',
            },
        ),
    ]
