# Generated by Django 5.2.12 on 2026-03-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAutoFetchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.IntegerField(choices=[(15, 'Every 15 minutes'), (30, 'Every 30 minutes'), (60, 'Every 1 hour'), (180, 'Every 3 hours'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Every 24 hours')], default=60)),
                ('use_proxyscrape', models.BooleanField(default=True)),
                ('use_geonode', models.BooleanField(default=True)),
                ('use_freeproxylist', models.BooleanField(default=False)),
                ('activate_on_load', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_added', models.IntegerField(default=0)),
                ('last_run_skipped', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Auto-Fetch Settings',
                'verbose_name_plural': 'Proxy Auto-Fetch Settings',
            },
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='botsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
