# Generated by Django 5.2.12 on 2026-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0002_proxyautofetchsettings_alter_botconfiguration_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketStreamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('cik', models.CharField(blank=True, default='', help_text='Your PacketStream CIK (Customer Identification Key) from the dashboard.', max_length=200, verbose_name='CIK / Password')),
                ('host', models.CharField(default='proxy.packetstream.io', max_length=200)),
                ('port', models.IntegerField(default=31112)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable PacketStream proxies as an option for bot sessions.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PacketStream Settings',
                'verbose_name_plural': 'PacketStream Settings',
            },
        ),
        migrations.AddField(
            model_name='botsession',
            name='proxy_source',
            field=models.CharField(choices=[('free', 'Free Proxies'), ('packetstream', 'PacketStream (Paid)'), ('none', 'No Proxy (Direct)')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_type',
            field=models.CharField(choices=[('free', 'Free Proxy'), ('packetstream', 'PacketStream (Paid)'), ('custom', 'Custom / Other')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='botsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proxyautofetchsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
